"""empty message

Revision ID: 9891ee6911a5
Revises: 799af52470ed
Create Date: 2024-04-02 15:44:32.113497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9891ee6911a5'
down_revision = '799af52470ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_file', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.drop_column('music_file')

    # ### end Alembic commands ###
